spring:
  application:
    name: list-api
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: list_api_db
      port: 27017
      host: localhost
      auto-index-creation: true # DiagnosticCollection.code

server:
  port: 8801
